[package]
name = "nesdie-collections"
version = "0.1.0"
edition = "2018"

[dependencies]
nesdie = { version = "0.1", path = "../" }
borsh = { version = "0.9", default-features = false }

[dev-dependencies]
rand = "0.7.2"
rand_xorshift = "0.2"

[features]
legacy = []
